name: room-assistant

on:
  push:
    paths:
      - 'room_assistant/**'
      - '.github/workflows/room-assistant.yml'
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Publish Home Assistant images
        uses: home-assistant/builder@2021.02.0
        with:
          args: |
            --all \
            --target /data/room_assistant
